### ISSUE TITLE
get_registered_tools() reads serverapp off the wrong ServerContext, so GET /mcp/tools/list has never exposed JupyterLab commands

### ISSUE THREAD

**Issue by ebarkhordar** [datalayer/jupyter-mcp-server#387]
`GET /mcp/tools/list` returns the FastMCP tools only. The allowlisted JupyterLab commands are never included, under any configuration, because the jupyter-mcp-tools lookup raises before the fetch is attempted.

`jupyter_mcp_server/server.py:1261` reads `serverapp` off the module-level `server_context`:

```python
if server_context.serverapp is not None:
    base_url = server_context.serverapp.connection_url
    token = server_context.serverapp.token
```

`server_context` is bound at `server.py:216` to `jupyter_mcp_server.server_context.ServerContext`, and that class defines no `serverapp`. The attribute belongs to the other `ServerContext`, at `jupyter_mcp_server/jupyter_extension/context.py:55`. The two classes share a name, which is why the block reads correctly.

The resulting `AttributeError` is caught by the `except Exception` at `server.py:1348`, which logs `Error querying jupyter-mcp-tools extension` and falls through to the FastMCP registry. Apart from that log line the failure is silent.

`handlers.py:145` performs the same lookup correctly, through `get_server_context()`.

## Reproduction

Clean `python:3.12-slim` container, editable install of the checkout at `280d1c8`, driving `get_registered_tools()` in `JUPYTER_SERVER` mode with `jupyterlab=True` and a one-entry allowlist, against a stand-in `jupyter_mcp_tools` that records the queries it receives:

```
PROVENANCE jupyter_mcp_server.__file__ = /work/jupyter_mcp_server/__init__.py
CONTEXT CLASS = jupyter_mcp_server.server_context.ServerContext
hasattr(server_context, 'serverapp') = False

LOG INFO  JupyterLab mode enabled, loading selected jupyter-mcp-tools
LOG ERROR Error querying jupyter-mcp-tools extension: 'ServerContext' object has no attribute 'serverapp'
Traceback (most recent call last):
  File "/work/jupyter_mcp_server/server.py", line 1261, in get_registered_tools
    if server_context.serverapp is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ServerContext' object has no attribute 'serverapp'

RESULT queries sent to jupyter-mcp-tools = []
RESULT JupyterLab tools returned = []
```

Expected: the allowlisted command is queried for and registered. Actual: the fetch is never attempted.

The stand-in only stands in for a running JupyterLab. The `AttributeError` fires before any fetch, so it does not depend on that substitution.

## Scope

`MCPSSEHandler.post` does its own inline fetch with the extension context, so `tools/list` over the MCP protocol is unaffected. The plain HTTP route `GET /mcp/tools/list` (`MCPToolsListHandler`, `handlers.py:596`) is the affected caller.

Nothing assigns `serverapp` onto `jupyter_mcp_server.server_context.ServerContext`: an AST parse for `*.serverapp` / `*._serverapp` assignments across the package returns four writers, all on other types (`LocalBackend.serverapp`, the extension app's `extension.serverapp`, and `_serverapp` on the `jupyter_extension.context.ServerContext` in its own `__init__`/`update()`/`reset()`). The string does not occur in `server_context.py` at all, so the branch has raised since it was written.

Introduced by e61f365 (#109), which added the integration. `git log -G 'server_context\.serverapp' --follow` returns that commit only, so there is no prior fix or revert to reconcile with.

I have a fix ready and will open it as a PR against this issue.
